<a href="https://colab.research.google.com/github/simranprajapati2/Microsoft-Training-2026/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Machine larning - Supervised  and Unsupervised ML
*work on past data/historical data ,find pattern and relation ship
*Supervised  types == Regression, classification
regression - linear regression, decision tree, rendom forest ,KNN, SVM,ridge regression, lasso reg
classification- logistic regression , dession tree, random forest, naive bayes,knn,svm
* Unsupervised types algo == K-mean,PCA, Aprior algorithm , DBSCAN CLUSTRING
 Boosting== lighrgbm,catboost,gradient bouster - not in scaler  algo



Numpy==used for numerical calculations, arrays, mathematical operations, and scientific computing.
Pandas==data manipulation, data cleaning, and data analysis. It is widely used in Data Science and Machine Learnin


**NUMPY**

In [ ]:
import numpy
marks=numpy.array([50,55,60,77])
print(marks)


[50 55 60 77]


In [ ]:
print(type(marks))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [ ]:
marks1=np.array([[23,45,77,55],[44,55,766,6666],[3,4,77,5,]]) #3D
print(marks1)

[[  23   45   77   55]
 [  44   55  766 6666]
 [   3    4   77    5]]


In [ ]:
import numpy as agenp
import numpy as np



In [83]:
np.array(30) #0 D



array(30)

In [ ]:
a=np.array([[1,2],[1,3]]) # 2 D
print(a)
b=np.array([1,2])#1 D
print(b)

[[1 2]
 [1 3]]
[1 2]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])

print(b.ndim)
print(b.shape)


2
(2, 3)


In [ ]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])


10


In [ ]:
#slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#data type

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:


arr = np.array([10, 20, 30])

print(arr.ndim)

1


In [84]:
arr.sum(axis=0)

np.int64(60)

In [ ]:


arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np

arr = np.array(['1', '2', '3'], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [ ]:
#copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#view

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:


arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:


arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print( (i, j), arr[i, j])

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:


arr = np.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
a=np.array([2,3])
b=np.array([3,4])
add= a+b
print(add)
sub= a-b
div= a/b
mul= a*b
print(sub)
print(div)
print(mul)


[5 7]
[-1 -1]
[0.66666667 0.75      ]
[ 6 12]


In [ ]:
a=np.array([[2,3],[2,4],[4,5]])
b=np.array([[3,4],[4,5],[5,6]])
add= a+b
print(add)
sub= a-b
div= a/b
mul= a*b
#mul1=a@b
print(sub)
print(div)
print(mul)
#print(mul1)

[[ 5  7]
 [ 6  9]
 [ 9 11]]
[[-1 -1]
 [-2 -1]
 [-1 -1]]
[[0.66666667 0.75      ]
 [0.5        0.8       ]
 [0.8        0.83333333]]
[[ 6 12]
 [ 8 20]
 [20 30]]


In [ ]:
 #tranposrt
print(a.T)

[[2 2 4]
 [3 4 5]]


In [ ]:
# np.linalg.inv(a) # This operation requires a square matrix
# np.linalg.det(a) # This operation requires a square matrix
# np.linalg.eig(a) # This operation requires a square matrix
np.linalg.matrix_rank(a)

np.int64(2)

In [ ]:
import numpy as np

# Create a 2x2 square matrix
square_matrix = np.array([[1, 2], [3, 4]])
print("Square Matrix:")
print(square_matrix)

Square Matrix:
[[1 2]
 [3 4]]


In [ ]:
# Calculate the determinant of the square matrix
determinant = np.linalg.det(square_matrix)
print("\nDeterminant of the matrix:", determinant)


Determinant of the matrix: -2.0000000000000004


Function -
np.mean()
np.max()
np.min()
np.mode()
vector
np.sqrt()
np.sum()
np.median()
np.std()


In [ ]:
import numpy as np

arr = np.array([10, 20, 20, 30, 40])

In [ ]:
print(np.mean(arr))

24.0


In [ ]:
print(np.max(arr))

40


In [ ]:
print(np.min(arr))

10


In [ ]:
print(np.median(arr))

20.0


In [ ]:
print(np.std(arr))

10.198039027185569


In [ ]:
arr = np.array([4, 9, 16, 25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


In [ ]:
arr = np.array([10, 20, 30])

print(np.sum(arr))

60


In [ ]:
v = np.array([3, 4])

print(v)

[3 4]


In [ ]:
from scipy import stats

arr = [10, 20, 20, 30, 40]

print(stats.mode(arr))

ModeResult(mode=np.int64(20), count=np.int64(2))


In [ ]:
#data type
myarr=np.array([2,4,5,6],np.int64)
print(myarr)
myarr[1]

[2 4 5 6]


np.int64(4)

In [ ]:
myarr.dtype

dtype('int64')

5 type Mechanism creating array
1 conversion from other python structure


In [ ]:
a1 = np.array([[1,2,3],[3,4,5],[4,5,6]])
a1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a1.dtype


dtype('int64')

In [ ]:
a1.shape

(3, 3)

In [ ]:
a1.size

9

2. intrinstic numpy array creation object

In [69]:
a2=np.zeros((2,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
lspace=np.linspace(1,4,20)
lspace

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [73]:
emp=np.empty((2,4))
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
el=np.empty_like(lspace)
el

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [75]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [76]:
ide.shape

(45, 45)

In [79]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [80]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [81]:
arr.ravel()
arr.shape

(99,)

In [85]:
ar=np.array([[2,3],[3,4]])
ar.flat


In [86]:
ar.T

array([[2, 3],
       [3, 4]])

In [88]:
for item in ar.flat:
  print(item)

2
3
3
4


In [89]:
ar.ndim

2

In [90]:
ar.size

4

In [91]:
ar.nbytes

32